config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
  	collection do
    	get 'recipe'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	def self.import_pictures
    	# **********************************************
		# *** Update or verify the following values. ***
		# **********************************************
		
		# Replace the accessKey string value with your valid access key.
		accessKey = "961bc5b2bb8e48c3885cb603219907b7"

		uri = URI('https://api.cognitive.microsoft.com/bing/v7.0/images/search')

		file = File.read('public/temp.json')
		js = JSON.parse(file)
		i = 0
		puts "Picking up where left off..."
		#puts JSON.pretty_generate(js)

		js["recipes"].each { |k, v|
			break if i >= 10
			#puts "Key=#{k}\n Value=#{v}"
			next if (js["recipes"][k]['imageURL'] != "")
			
			term = js["recipes"][k]["title"].downcase.gsub(/[^a-z0-9\s]/i, '')

			uri.query = URI.encode_www_form({
			    # Request parameters
			    'q' => term,
			    'count' => '2',
			    'offset' => '0',
			    'mkt' => 'en-us',
			    'safeSearch' => 'Moderate'
			})

			request = Net::HTTP::Get.new(uri.request_uri)
			# Request headers
			request['Ocp-Apim-Subscription-Key'] = accessKey
			
			response = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
			    http.request(request)
			end

			newobj = JSON.parse(response.body)

			begin
				thumbnail = newobj["value"][0]["thumbnailUrl"].chomp('&pid=Api')
				js["recipes"][k]["imageURL"] = thumbnail
				puts "Added imageURL to #{k}"
				i = i + 1
			rescue
				puts "Bad server response at #{k}... skipping for now"
			end
			
		}
		puts "Writing new file.. (final)."
		File.open("public/temp.json","w") do |f|
		  f.write(JSON.pretty_generate(js))
		end	
		puts "New file successfully built"
    end
    def self.generate_recipe_obj
    	Recipe.delete_all
    	file = File.read('public/recipes.json')
    	recipe = Recipe.new(id: 0, title: file)
    	recipe.save
    end
	def self.import_pictures_to_database
    	# **********************************************
		# *** Update or verify the following values. ***
		# **********************************************
		
		# Replace the accessKey string value with your valid access key.
		accessKey = "961bc5b2bb8e48c3885cb603219907b7"

		uri = URI('https://api.cognitive.microsoft.com/bing/v7.0/images/search')
		recipe = Recipe.find(0)
		js = JSON.parse(recipe.title)
		i = 0
		puts "Picking up where left off..."
		#puts JSON.pretty_generate(js)

		js["recipes"].each { |k, v|
			break if i >= 10
			#puts "Key=#{k}\n Value=#{v}"
			next if (js["recipes"][k]['imageURL'] != "")
			
			term = js["recipes"][k]["title"].downcase.gsub(/[^a-z0-9\s]/i, '')

			uri.query = URI.encode_www_form({
			    # Request parameters
			    'q' => term,
			    'count' => '2',
			    'offset' => '0',
			    'mkt' => 'en-us',
			    'safeSearch' => 'Moderate'
			})

			request = Net::HTTP::Get.new(uri.request_uri)
			# Request headers
			request['Ocp-Apim-Subscription-Key'] = accessKey
			
			response = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
			    http.request(request)
			end

			newobj = JSON.parse(response.body)

			begin
				thumbnail = newobj["value"][0]["thumbnailUrl"].chomp('&pid=Api')
				js["recipes"][k]["imageURL"] = thumbnail
				puts "Added imageURL to #{k}"
				i = i + 1
			rescue
				puts "Bad server response at #{k}... skipping for now"
			end
			
		}
		puts "Updating database.. (final)."
		recipe.update_attributes(title: JSON.generate(js))
		puts "Recipe object successfully updated"
    end

    def self.generate
		file = File.read('public/ingredients_and_recipes.json')
		all = JSON.parse(file)

		file = File.read('public/ingredients.json')
		ings = JSON.parse(file)
		i = 0
		all['ingredients'].each{ |k, v|
			ings['ingredientRecipes'][k]['recipesUsing'] = {};
			ingname = v['name'].downcase.gsub(/[^a-z]/,'')
			puts "Filtered ingredient name: " + ingname

			all['recipes'].each{ |ktwo, vtwo|
				vtwo['cookingIngredients'].each { |x|
					listname = x.downcase.gsub(/[^a-z]/,'')
					if listname.include? ingname
						puts "RECIPE FOUND. ADDING TO RECIPESUSING:"
						ings['ingredientRecipes'][k]['recipesUsing'][ktwo] = vtwo['title'];
						break
					end
				}
			}
			i = i+1
		}
		puts "Writing new file.. (final)."
		File.open("public/ingredientRecipes.json","w") do |f|
		  f.write(JSON.generate(ings))
		end	
		puts "New file successfully built"
    end

    def self.convert
    	file = File.read('public/somewhat_completed.json');
		old = JSON.parse(file);
		file = File.read('public/recipes.json');
		newjs = JSON.parse(file);
		i = 0
		old['recipes'].each{ |k, v|
			break if i >= 420
			if (v['imageURL'] != "")
				newjs["recipes"][k]["imageURL"] = v['imageURL']
			end
			i = i+1
		}
		puts "Writing new file.. (final)."
		File.open("public/recipes.json","w") do |f|
		  f.write(JSON.pretty_generate(newjs))
		end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
  
  end
  def recipe
    @recipe = Recipe.first
  end
      # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :url, :numFavorites, :imageurl)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JsonTesting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :recipe_title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :recipe_url %>
  </div>

  <div class="field">
    <%= form.label :numFavorites %>
    <%= form.number_field :numFavorites, id: :recipe_numFavorites %>
  </div>

  <div class="field">
    <%= form.label :imageurl %>
    <%= form.text_field :imageurl, id: :recipe_imageurl %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<a href="/recipes/recipe">Click for most recently automated recipes json (with imageURLs)</a> (<%= Recipe.first.updated_at.strftime("%m-%e-%y %I:%M %p") %>)
<br><br>
<a href="/ingredients.json">Click for /ingredients.json</a>
<br><br>
<a href="/recipes.json">Click for /recipes.json</a>
<br><br>
<a href="/ingredientRecipes.json">Click for /ingredientRecipes.json</a>
<br><br>
<a href="/recipease_final.json">Click for merged, final recipease json (/ingredients, /recipes, /ingredientRecipes, /users)</a>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/recipe.html.erb
ctrl-f for <b><i>"imageURL": "https</i></b> to see how many records currently have an imageURL. Should be done by 3/29.<br><br><br>

<%= JSON.pretty_generate(JSON.parse(@recipe.title)) %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @recipe.url %>
</p>

<p>
  <strong>Numfavorites:</strong>
  <%= @recipe.numFavorites %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @recipe.imageurl %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>